config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  resources :users do
    resources :relationships
    resources :stories
    resources :profiles
  end

  resources :relationships

  resources :stories

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :user_id, uniqueness: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User", foreign_key: 'following_id'
  belongs_to :following, class_name: "User", foreign_key: 'follower_id'
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :contributions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :contributions
  has_many :following_through, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy
  has_many :follower_through, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :follower_through, source: :follower
  has_many :followers, through: :following_through, source: :following
  has_many :followings_stories, through: :followings, source: :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

  def followed_by user
    followers.include? user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :mailbox, :conversation

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @profile = Profile.find(current_user.id)
  end

  def update
    @profile = Profile.find(current_user.id)
    if @profile.update(profile_params)
      redirect_to user_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :tagline, :aboutme, :genres)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    Relationship.create relationship_params
    redirect_to :back
  end

  def destroy
    target = Relationship.find_by relationship_params
    if target
      target.destroy
      redirect_to :back
    else
      flash[:error] = "No such relationship"
      redirect_to :back
    end
  end

  private

    def relationship_params
      params.require(:relationship).permit(:following_id, :follower_id)
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to user_path(current_user)
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  private

    def story_params
      params.require(:story).permit(:title, :genre, :body, :user_id, :authors)
    end
end

app/controllers/users.rb
class UsersController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @profile = Profile.find(@user.id)
    @stories = Story.where(user_id: @user.id).order(created_at: :desc)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!


  include WelcomeHelper
  def index
    @following = Relationship.where(follower_id: current_user.id)
    @profile = Profile.find_or_create_by!(user_id: current_user.id)
    @feed = current_user.stories + current_user.followings_stories
    @stories = @feed.sort_by(&:created_at).reverse
  end

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_or_unfollow user
    if user.followed_by current_user
      render partial: 'unfollow', locals: {user: user}
    else
      render partial: 'follow', locals: {user: user}
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<div class="profile-content col-md-10 col-md-offset-1">

<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>
</div>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<%= render 'shared/navbar' %>
<br><br>
<div class="profile-content col-md-10 col-md-offset-1">


    <div class="row">
      <div class="spacer">
        <!-- we'll configure this to compose new conversations later -->
         <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %><br><br>
      </div>
    </div>

      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'mailbox/folders' %>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render partial: 'messages' %>
          </div>

        </div>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skitschy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/mailbox/_folder_view.html.erb
<%= render 'shared/navbar' %>
<br><br>
<div class="profile-content col-md-10 col-md-offset-1">


    <div class="row">
      <div class="spacer">
        <!-- we'll configure this to compose new conversations later -->
         <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %><br><br>
      </div>
    </div>

      <div class="col-md-4">
        <div  class="panel panel-default">
          <div class="panel-body">
            <%= render 'mailbox/folders' %>
          </div>
        </div>
      </div>

      <div class="col-md-8">

            <% if is_conversation %>
              <%= render 'conversations/form' %>
            <% else %>
              <%= render partial: 'conversations/conversation', collection: messages %>

            <% end %>
            <!-- individual conversations will show here -->

      </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>

app/views/profiles/edit.html.erb
<%= render "shared/navbar" %>

<br><br>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
      <center>
        <%= render "shared/profile_edit" %>
      <center>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SKITschy', '/', class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Browse Stories', stories_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><a href="#">Settings</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_profile_edit.html.erb
<br>

<h2>Update Profile</h2>
<br>

<%= form_for @profile, url: user_profile_path do |f| %>
    <div id="error_group">
      <% if @profile.errors.any? %>
          <h2>
            <%= pluralize(@profile.errors.count, "error")%>prohibited this lesson from being posted:
          </h2>
          <ul>
            <% @profile.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
      <% end %>
    </div>


      <p>
        <%= f.label :username %><br>
        <%= f.text_field :username %>
      </p>

      <p>
        <%= f.label :tagline %><br>
        <%= f.text_field :tagline %>
      </p>

      <p>
        <%= f.label :aboutme %><br>
        <%= f.text_area :aboutme %>
      </p>

      <p>
        <%= f.label :genres %><br>
        <%= f.text_area :genres %>
      </p>

      <p>
        <%= f.submit 'Update', class: "btn btn-success" %>
      </p>

      <br>

<% end %>

app/views/shared/_story_form.html.erb
<%= form_for Story.new do |f| %>
  <p>
    <input type="hidden" value="<%= current_user.id %>" name="story[user_id]">
  </p>

  <p>
    <input type="hidden" value="<%= @profile.username %>" name="story[authors]">
  </p>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit 'Okay!' %>
  </p>
<% end %>

app/views/stories/index.html.erb
<%= render "shared/navbar" %>

<br><br>

<div class="container">
  <div class="story-head">
    <h2>Stories</h2>
  </div>
  <% @stories.each do |story| %>
    <div class="story"><%= link_to story.title, story_path(story) %></div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div class="container">
  <%= render "shared/story_form" %>

app/views/stories/show.html.erb
<%= render 'shared/navbar' %>

  <br><br>

<div class="col-md-6 col-md-offset-3">
  <div class="profile-content">
    <h1><%= @story.title %></h1>
    <h4>By: <%= @story.authors %></h3>
    <h4>Title: <%= @story.genre %></h3>
    <p><%= @story.body %></p>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for Relationship.new do |f| %>
  <input type="hidden" value="<%= current_user.id %>" name="relationship[follower_id]">
  <input type="hidden" value="<%= user.id %>" name="relationship[following_id]">

  <%= f.submit "Follow", :class => 'btn btn-success' %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_tag user_relationship_path(current_user, user), method: "delete" do |f| %>
    <input type="hidden" value="<%= current_user.id %>" name="relationship[follower_id]">
    <input type="hidden" value="<%= user.id %>" name="relationship[following_id]">
  <%= submit_tag "Unfollow", :class => 'btn btn-success' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <li><%= link_to user.profile.username, user_path(user.id) %></li>
<% end %>

app/views/users/show.html.erb
<%= render "shared/navbar" %>

<br><br>

<div class="row profile">
<div class="col-md-3">
  <div class="profile-sidebar">
    <!-- SIDEBAR USERPIC -->
    <div class="profile-userpic">
      <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
    </div>
    <!-- END SIDEBAR USERPIC -->
    <!-- SIDEBAR USER TITLE -->
    <div class="profile-usertitle">
      <div class="profile-usertitle-name">
        <%= @profile.username %>
      </div>
      <div class="profile-tagline">
        <%= @profile.tagline %>
      </div>
      <div class="profile-aboutme">
        <strong>About Me</strong><br>
        <p><%= @profile.aboutme %></p>
      </div>
      <div class="profile-genres">
        <strong>Genres I enjoy:</strong><br>
        <p><%= @profile.genres %></p>
      </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR BUTTONS -->
    <div class="profile-userbuttons">
      <% if current_user == @user %>
        <%= link_to 'Edit Profile', edit_user_profile_path(@user.id, @user.id), class: "btn"%>
      <% else %>
        <%= follow_or_unfollow @user %><br>
        <button type="button" class="btn btn-danger btn-sm">Message</button>
      <% end %>
    </div>
    <!-- END SIDEBAR BUTTONS -->
  </div>
</div>
<div class="col-md-9">
  <div class="profile-content">
    <div class="list-group">
      <% @stories.each do |story| %>
        <a href="/stories/<%= story.id %>" class="list-group-item">
          <h4 class="list-group-item-title"><strong><%= story.title %></strong></h4>
          <h6 class="list-group-item-author"><strong>By:</strong> <%= story.authors %></h6>
          <h6 class="list-group-item-genre"><strong>Genre:</strong> <%= story.genre %></h6>
          <p class="list-group-item-text"><%= story.body %></p>
        </a>
      <% end %>
     </div>
    </div>
  </div>
</div>
</div>

app/views/welcome/_story_form.html.erb
<%= form_for @story, url: new_user_story_path  do |f| %>
  <div id="error_group">
    <% if @story.errors.any? %>
      <h3>
        <%= pluralize(@story.errors.count, "error")%>kept this story from being saved!
      </h3>
      <ul>
        <% @story.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit 'Print!' %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<%= render "shared/navbar" %>
<br><br>
<div class="row profile">
<div class="col-md-3">
  <div class="profile-sidebar">
    <!-- SIDEBAR USERPIC -->
    <div class="profile-userpic">
      <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
    </div>
    <!-- END SIDEBAR USERPIC -->
    <!-- SIDEBAR USER TITLE -->
    <div class="profile-usertitle">
      <div class="profile-usertitle-name">
        <% if @profile.username %>
          Hey, <%= @profile.username %> !
        <% else %>
          Hey, you!
        <% end %>
      </div>
      <div class="profile-usertitle-job">
        <%= link_to 'Edit Profile', edit_user_profile_path(current_user.id, current_user.id), class: "btn"%>

      </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR BUTTONS -->
    <div class="profile-userbuttons">
      <center>
        <a href="/mailbox/inbox" class="btn btn-success btn-lg">Notes <span class="badge">1</badge></a>

          <br><br>
      <!-- Trigger the modal with a button -->
      <button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">Write Something! </button>

      <!-- Modal -->
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-lg">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Write a story:</h4>
            </div>
            <div class="modal-body">
              <%= render 'shared/story_form' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>

      <center>
    </div>
  </div>
</div>
<div class="col-md-9">
  <div class="profile-content">
    <div class="list-group">
      <% @stories.each do |story| %>
        <a href="/stories/<%= story.id %>" class="list-group-item">
          <h4 class="list-group-item-title"><strong><%= story.title %></strong></h4>
          <h6 class="list-group-item-author"><strong>By:</strong> <%= story.authors %></h6>
          <h6 class="list-group-item-genre"><strong>Genre:</strong> <%= story.genre %></h6>
          <p class="list-group-item-text"><%= story.body %></p>
        </a>
      <% end %>
     </div>
    </div>
  </div>
</div>